INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('egestas','purus gravida sagittis. Duis gravida.','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('tristique neque venenatis','amet, dapibus  blandit at,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ante ipsum primis','ac libero nec ligula consectetuer rhoncus.','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('euismod enim. Etiam gravida molestie arcu. Sed eu','tempor bibendum. Donec felis orci,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('tincidunt orci quis lectus. Nullam suscipit, est ac facilisis','Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ipsum leo elementum sem, vitae aliquam eros','elit. Aliquam auctor, velit eget','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('penatibus','Curabitur ut','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('non','erat vitae risus. Duis a mi fringilla mi lacinia','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('vitae, sodales','velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('eu dolor egestas','consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.','dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nec, malesuada ut, sem. Nulla interdum.','aliquet odio. Etiam ligula','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('non dui nec urna suscipit nonummy.','Fusce aliquet magna a neque. Nullam ut nisi','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('arcu.','pede ac urna. Ut tincidunt vehicula risus. Nulla eget','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('sed libero. Proin sed turpis nec mauris blandit mattis. Cras','Phasellus ornare. Fusce mollis. Duis sit amet diam','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Sed nunc est, mollis non, cursus','nibh. Phasellus nulla. Integer vulputate,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('risus quis diam luctus lobortis.','tellus faucibus leo, in lobortis tellus justo','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ligula elit, pretium et, rutrum non, hendrerit  ante. Nunc','erat volutpat. Nulla dignissim. Maecenas ornare','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('arcu imperdiet ullamcorper. Duis at lacus. Quisque purus','sociosqu ad litora torquent','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ultricies','vitae','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('arcu et pede. Nunc sed orci','rutrum. Fusce dolor quam, elementum','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('sit amet, consectetuer adipiscing elit. Curabitur','feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh.','facilisis. Suspendisse commodo','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('suscipit, est ac facilisis facilisis,','vitae diam. Proin dolor. Nulla semper tellus id','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque,','magna nec quam. Curabitur vel lectus. Cum sociis natoque','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam','tellus sem mollis dui, in sodales elit erat vitae','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('primis in faucibus orci luctus et ultrices posuere cubilia','augue ac ipsum. Phasellus vitae mauris sit amet lorem','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et','sollicitudin','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere','in magna. Phasellus dolor elit, pellentesque a, facilisis non,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('vitae velit egestas lacinia. Sed congue, elit sed consequat auctor,','adipiscing lacus. Ut','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl.','ridiculus mus. Proin vel arcu','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nec','neque. Morbi','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('non, dapibus rutrum,','metus. Aenean','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('vitae semper egestas, urna justo faucibus','natoque penatibus','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('pellentesque, tellus sem mollis dui,','sapien, gravida non, sollicitudin a, malesuada','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('erat. Vivamus nisi. Mauris','amet ultricies sem magna nec quam. Curabitur','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ultricies dignissim lacus. Aliquam rutrum lorem','convallis, ante lectus','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('non','a purus. Duis elementum,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Sed et libero. Proin mi. Aliquam gravida mauris ut','Suspendisse aliquet molestie','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim','Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim','imperdiet dictum magna. Ut tincidunt','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Class aptent taciti','elementum sem, vitae aliquam eros turpis non enim. Mauris quis','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('faucibus leo, in','Integer eu lacus. Quisque','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('habitant morbi tristique senectus et netus et','vel quam dignissim pharetra. Nam ac nulla. In','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nibh. Quisque nonummy ipsum','Curae; Phasellus ornare. Fusce mollis.','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec','Morbi non sapien','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor.','Quisque ornare tortor at risus. Nunc','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.','ac metus vitae velit egestas lacinia. Sed congue,','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('risus. Donec egestas.','malesuada','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Donec elementum, lorem ut aliquam iaculis,','risus a ultricies adipiscing, enim mi','true');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('et ultrices','ante dictum mi, ac mattis velit','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nec urna et arcu imperdiet ullamcorper. Duis at','ac, feugiat non, lobortis quis, pede. Suspendisse','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('rhoncus. Proin','mus. Donec dignissim','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus','Etiam laoreet, libero et tristique','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('magnis dis parturient montes, nascetur','nec,','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('enim nec tempus scelerisque,','adipiscing lobortis risus. In','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('fames ac turpis egestas.','placerat velit. Quisque varius. Nam porttitor scelerisque neque.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('non massa non ante bibendum ullamcorper. Duis','Mauris non','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('In lorem. Donec','erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('tempus risus. Donec egestas. Duis ac arcu.','tempor','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('eu,','Praesent luctus. Curabitur egestas nunc sed libero. Proin sed','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('quis lectus. Nullam suscipit, est','Phasellus ornare. Fusce mollis. Duis sit amet','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Donec felis orci, adipiscing non, luctus sit amet,','Nunc ut erat.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('urna. Nunc quis arcu vel quam dignissim','Suspendisse aliquet molestie tellus. Aenean egestas','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('eget metus eu erat semper rutrum. Fusce dolor quam, elementum','urna','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('a, auctor non,','tristique pharetra. Quisque ac','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('eu','consequat dolor vitae dolor.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Suspendisse aliquet,','amet, consectetuer adipiscing elit. Aliquam auctor, velit','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi','lobortis quis, pede. Suspendisse dui. Fusce diam nunc,','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('lacus. Nulla tincidunt, neque vitae','non, vestibulum nec, euismod in, dolor. Fusce feugiat.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Cras vehicula aliquet libero.','mi','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ipsum. Suspendisse sagittis. Nullam vitae diam.','non justo. Proin non massa non ante bibendum ullamcorper. Duis','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('neque.','risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nunc risus varius orci, in consequat enim','cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('amet, consectetuer adipiscing','vitae aliquam eros turpis','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor,','hendrerit a, arcu. Sed et libero.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('purus','lobortis tellus','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('at auctor ullamcorper, nisl arcu','eu eros. Nam consequat dolor vitae','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('senectus et netus et malesuada fames ac turpis egestas. Aliquam','posuere','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('pede.','Aliquam','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nisi nibh lacinia orci,','blandit enim consequat purus. Maecenas libero','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('elit. Etiam laoreet, libero','tempus risus.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('erat volutpat.','urna. Nunc quis arcu vel quam','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('eros. Nam consequat dolor vitae dolor. Donec fringilla.','erat eget ipsum. Suspendisse sagittis.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('ridiculus','malesuada vel, venenatis vel,','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('quis, pede. Praesent eu dui.','vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nunc. Quisque ornare tortor','pede','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('aptent taciti','ligula tortor, dictum eu, placerat eget,','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit','adipiscing. Mauris molestie','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nulla vulputate dui, nec tempus mauris','sem magna nec quam. Curabitur','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('vitae, erat. Vivamus nisi.','at, nisi. Cum sociis natoque penatibus et','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('neque sed dictum eleifend, nunc risus varius','mollis non, cursus non, egestas a,','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('mi enim, condimentum eget, volutpat ornare, facilisis eget,','tellus sem mollis dui, in sodales elit','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('pede, nonummy','tortor nibh sit amet orci. Ut','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('Duis at lacus. Quisque purus sapien,','dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('orci. Ut semper pretium neque. Morbi quis','nisl. Quisque fringilla euismod enim.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('arcu eu odio tristique pharetra. Quisque ac libero nec','dignissim pharetra. Nam ac nulla.','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('a tortor. Nunc commodo auctor velit.','cursus','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('nisi','eget lacus. Mauris non dui nec urna suscipit','false');
INSERT INTO "tasks" (assignment,notes,iscomplete) VALUES ('auctor','Cum sociis natoque','false');
